import { redirect } from 'next/navigation';
import { currentUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { getProducts } from '@/lib/data';
import { AdminConsole } from '@/components/admin-console';
import { ActivityChart } from '@/components/charts';
export const metadata = { title: 'Admin Dashboard', robots: { index: false, follow: false } };
export default async function Admin() { const user = await currentUser(); if (!user)
    redirect('/login?callbackUrl=/admin'); if (user.role !== 'ADMIN')
    return <main className="not-found"><h1>Administrator access required.</h1><p>This account doesn’t have access to the admin dashboard.</p></main>; const [categories, products, reviews, users, reports, ratings, ranked] = await Promise.all([db.category.findMany({ orderBy: { name: 'asc' } }), db.product.findMany({ orderBy: { name: 'asc' } }), db.review.findMany({ include: { user: { select: { username: true } }, product: { select: { name: true } } }, orderBy: { createdAt: 'desc' } }), db.user.findMany({ select: { id: true, username: true, email: true, role: true, disabled: true } }), db.report.findMany({ include: { user: { select: { username: true } }, review: { select: { title: true, content: true } } }, orderBy: { createdAt: 'desc' } }), db.rating.findMany({ select: { createdAt: true } }), getProducts()]); const activity = Array.from({ length: 14 }, (_, i) => { const date = new Date(Date.now() - (13 - i) * 86400000); const day = date.toISOString().slice(0, 10); return { day: day.slice(5), ratings: ratings.filter(r => r.createdAt.toISOString().startsWith(day)).length }; }); const mostRated = [...ranked].sort((a, b) => b.count - a.count)[0]; const activeCategory = categories.map(c => ({ name: c.name, count: ranked.filter(p => p.category.id === c.id).reduce((n, p) => n + p.count, 0) })).sort((a, b) => b.count - a.count)[0]; return <main className="container page"><header className="page-heading"><span className="eyebrow">COMMUNITY CONTROL CENTER</span><h1>Keep good things growing.</h1><p>Manage the catalog, support the community, and understand what’s happening.</p></header><div className="stat-grid">{[['Users', users.length], ['Ratings', ratings.length], ['Reviews', reviews.length], ['Open reports', reports.filter(r => r.status === 'OPEN').length]].map(([label, value]) => <div className="panel stat" key={label}><strong>{value}</strong><small>{label}</small></div>)}</div><div className="panel"><h2>Rating activity</h2><p className="muted">Last 14 days · {activity.slice(-7).reduce((sum, d) => sum + d.ratings, 0)} ratings this week</p><ActivityChart data={activity}/><p className="hint">Most rated: {mostRated?.name || '—'} · Highest ranked: {ranked[0]?.name || '—'} · Most active category: {activeCategory?.name || '—'}</p></div><AdminConsole categories={categories} products={products} reviews={reviews} users={users} reports={reports}/></main>; }
