import Link from 'next/link';
import { notFound } from 'next/navigation';
import { db } from '@/lib/db';
import { currentUser } from '@/lib/auth';
import { Stars } from '@/components/product-card';
type Props = {
    params: Promise<{
        username: string;
    }>;
};
export async function generateMetadata({ params }: Props) { const { username } = await params; return { title: `${username} — Community Profile`, description: `Read ${username}’s product ratings and reviews on ReviewEngine.` }; }
export default async function Profile({ params }: Props) { const { username } = await params; const [user, viewer] = await Promise.all([db.user.findUnique({ where: { username }, select: { id: true, username: true, avatar: true, isSample: true, createdAt: true, ratings: { include: { product: { select: { name: true, slug: true } } }, orderBy: { updatedAt: 'desc' } }, reviews: { where: { approved: true }, include: { product: { select: { name: true, slug: true } } }, orderBy: { updatedAt: 'desc' } } } }), currentUser()]); if (!user)
    notFound(); return <main className="container page"><header className="profile-header"><span className="avatar">{user.avatar ? <img src={user.avatar} alt={`${username} avatar`}/> : username.slice(0, 2).toUpperCase()}</span><div><span className="eyebrow">{user.isSample ? 'SAMPLE COMMUNITY PROFILE' : 'COMMUNITY PROFILE'}</span><h1>{username}</h1><p>Member since {user.createdAt.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p></div>{viewer?.id === user.id && <Link className="button secondary" href="/settings">Edit profile</Link>}</header><div className="stat-grid"><div className="panel stat"><strong>{user.ratings.length}</strong><small>Ratings shared</small></div><div className="panel stat"><strong>{user.reviews.length}</strong><small>Reviews written</small></div></div><div className="detail-grid"><section className="panel"><h2>Recent reviews</h2>{!user.reviews.length && <p className="muted">No reviews yet.</p>}{user.reviews.map(r => <article className="review-item" key={r.id}><Link className="text-link" href={`/product/${r.product.slug}`}>{r.product.name}</Link><div style={{ marginTop: 8 }}><Stars value={r.rating}/></div><h3>{r.title}</h3><p>{r.content}</p>{viewer?.id === user.id && <Link className="text-link" style={{ marginTop: 15 }} href={`/product/${r.product.slug}#rate`}>Edit or delete my review</Link>}</article>)}</section><section className="panel"><h2>Rating activity</h2>{!user.ratings.length && <p className="muted">Your next great discovery is waiting.</p>}{user.ratings.map(r => <div className="activity-row" key={r.id}><div><Link href={`/product/${r.product.slug}${viewer?.id === user.id ? '#rate' : ''}`}>{r.product.name}</Link><p className="hint" style={{ margin: 0 }}>{r.updatedAt.toLocaleDateString('en-US')}</p></div><Stars value={r.overall}/></div>)}</section></div></main>; }
