import 'dotenv/config';
import {PrismaClient} from '../generated/prisma/client';
import {PrismaPg} from '@prisma/adapter-pg';
import {hash} from 'bcryptjs';
import {randomBytes} from 'node:crypto';
import {catalog} from './catalog';
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
async function main(){
 if(process.env.SEED_DEMO!=='true')throw Error('Set SEED_DEMO=true explicitly to create sample data.');
 const password=await hash(randomBytes(32).toString('hex'),12);
 const names=['alex_river','maya_designs','jordan_dev','sam_explores','riley_notes','taylor_codes','casey_creates','morgan_reads','jamie_runs','avery_writes','robin_listens','skyler_builds','quinn_plays','drew_discovers','dakota_draws','reese_reviews','cameron_works','parker_learns','finley_shares','rowan_thinks','harper_tests','emery_makes','sage_travels','blake_browses','elliot_jams','jesse_watches','noah_creates','aria_discovers','leo_codes','ivy_designs','milo_reviews','luna_learns','nova_builds','kai_explores','ruby_reads','theo_tests','jules_writes','river_runs','eden_creates','remy_lists'];
 const users=[];for(const username of names)users.push(await db.user.upsert({where:{email:`${username}@sample.reviewengine.invalid`},create:{username,email:`${username}@sample.reviewengine.invalid`,passwordHash:password,isSample:true,createdAt:new Date(Date.now()-90*86400000)},update:{}}));
 let index=0;for(const group of catalog){const category=await db.category.upsert({where:{slug:group.slug},create:{name:group.name,slug:group.slug,description:group.description},update:{}});for(const [name,slug,websiteUrl,description,color]of group.products){const product=await db.product.upsert({where:{slug},create:{name,slug,websiteUrl,description,color,categoryId:category.id,pros:['A focused experience for everyday use','An active ecosystem and familiar workflow'],cons:['The best fit depends on your workflow','Some features or options may require a paid plan']},update:{}});const count=24+(index*7)%17;for(let i=0;i<count;i++){const roll=(i*17+index*11)%100;const overall=roll<56?5:roll<87?4:roll<96?3:2;const detail=(offset:number)=>Math.max(1,Math.min(5,overall+((i+offset)%7===0?-1:0)));const createdAt=new Date(Date.now()-((i*3+index)%25)*86400000-(i+index)*360000);const key={userId:users[i].id,productId:product.id};await db.rating.upsert({where:{userId_productId:key},create:{...key,overall,easeOfUse:detail(1),features:detail(2),performance:detail(3),value:detail(4),userExperience:detail(5),createdAt},update:{}});if(i<8){const texts=[['Easy to make part of my routine',`I tried ${name} while comparing a few alternatives. The everyday experience has been straightforward, and I keep coming back to it. I would still suggest trying it with your own workflow before committing.`],['A useful tool, with a few trade-offs',`${name} works well for my regular tasks. I like having the basics within reach, although there are moments when I wish the settings were easier to navigate.`],['A good fit for how I work',`After spending some time with ${name}, I appreciate the familiar layout and the overall experience. It is worth comparing a couple of options to see which feels right for you.`],['Glad I gave it a try',`I came to ${name} after reading community reviews. There is a little learning involved, but I have found a routine that works for me. Some extra customization would make it even better.`]];const [title,content]=texts[(i+index)%texts.length];await db.review.upsert({where:{userId_productId:key},create:{...key,rating:overall,title,content,createdAt},update:{}});}}index++;}}
 console.log(`Seeded ${catalog.length} categories, ${index} products, and ${users.length} clearly labeled sample reviewers. No sample user has a known login password.`);
 if(process.env.SEED_ADMIN_EMAIL&&process.env.SEED_ADMIN_PASSWORD){if(process.env.SEED_ADMIN_PASSWORD.length<12)throw Error('SEED_ADMIN_PASSWORD must have at least 12 characters.');await db.user.upsert({where:{email:process.env.SEED_ADMIN_EMAIL.toLowerCase()},create:{username:'admin',email:process.env.SEED_ADMIN_EMAIL.toLowerCase(),passwordHash:await hash(process.env.SEED_ADMIN_PASSWORD,12),role:'ADMIN'},update:{}});console.log('Created the requested development admin if it did not exist.');}
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.$disconnect());
