'use client';
import { useState } from 'react';
import type { ProductSummary } from '@/lib/data';
import { ProductRow, ProductCard } from './product-card';
export function Catalog({ products, initial = 'weighted', rows = true }: {
    products: ProductSummary[];
    initial?: string;
    rows?: boolean;
}) { const [sort, setSort] = useState(initial), [category, setCategory] = useState('all'); const categories = [...new Set(products.map(p => p.category.name))]; const sorted = products.filter(p => category === 'all' || p.category.name === category).sort((a, b) => sort === 'reviewed' ? b.reviewCount - a.reviewCount : sort === 'trending' ? b.trending - a.trending : sort === 'newest' ? +new Date(b.createdAt) - +new Date(a.createdAt) : sort === 'lowest' ? a.average - b.average : sort === 'popular' ? b.count - a.count : b.weighted - a.weighted); return <><div className="catalog-controls"><span className="muted">{sorted.length} products to discover</span><div><select aria-label="Filter category" value={category} onChange={e => setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(c => <option key={c}>{c}</option>)}</select><select aria-label="Sort products" value={sort} onChange={e => setSort(e.target.value)}><option value="weighted">Highest rated</option><option value="reviewed">Most reviewed</option><option value="trending">Fastest rising</option><option value="popular">Most popular</option><option value="newest">Newest</option><option value="lowest">Lowest rated</option></select></div></div><div className={rows ? 'product-list' : 'product-grid'}>{sorted.map((p, i) => rows ? <ProductRow key={p.id} product={p} rank={i + 1}/> : <ProductCard key={p.id} product={p}/>)}</div>{!sorted.length && <div className="empty"><h3>A little quiet here, for now.</h3><p>New products will appear here as the community grows.</p></div>}</>; }
